version: '3.8'

services:
  # Serviço Ruby
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Serviço PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cardapioDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  # Serviço pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "5050:80"
    depends_on:
      - db
